language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo clean
  - hexo g
  - cp ./CNAME ./public/CNAME
  - cd ./public
  - sed -i "/<meta charset=\"UTF-8\">/a\    <meta name=\"google-site-verification\" content=\"${GOOGLE_VERIFICATION}\"/>" index.html
  - git init
  - git config user.name "Elvis"
  - git config user.email "levgcsc@gmail.com"
  - git add .
  - git commit -m "Feat/deploy Jasmine"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/lev-gc/lev-gc.github.io.git" master:master

branches:
  only:
    - source
