language: node_js
node_js: 12.18.3

install:
  - yarn

script:
  - yarn c
  - yarn b
  - cp ./CNAME ./dist/CNAME
  - cd ./dist
  - sed -i "/<meta charset=\"UTF-8\">/a\    <meta name=\"google-site-verification\" content=\"${GOOGLE_VERIFICATION}\"/>" index.html
  - git init
  - git config user.name "Elvis"
  - git config user.email "levgcsc@gmail.com"
  - git add .
  - git commit -m "Feat/deploy Jasmine"
  - git push --force --quiet "https://${GITHUB_TOKEN}@github.com/lev-gc/lev-gc.github.io.git" master:master

branches:
  only:
    - source
