# Site
title: Jasmine
subtitle: Fear always springs from ignorance.
description:
keywords:
author: Elvis Chan
language: default
timezone: Asia/Shanghai

# URL
url: https://lev-gc.github.io/
root: /
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

# Directory
source_dir: source
public_dir: dist
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
auto_spacing: false
titlecase: false
external_link:
  enable: true
  field: site
  exclude: []
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: false
highlight:
  enable: true
  auto_detect: false
  line_number: true
  tab_replace: ''
  wrap: true
  hljs: false

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date/Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: date

# Pagination
per_page: 5
pagination_dir: page

# Deployment
deploy:
  type: git
  repo: https://github.com/lev-gc/lev-gc.github.io.git
  branch: master
  name: Elvis
  email: levgcsc@gmail.com
  # message: Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}

# Theme
theme: jasmine
## config of theme jasmine
theme_config:
  github_link: https://github.com/lev-gc
