name: github-pages

# Triggers
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows to run from the Actions tab
  workflow_dispatch:

# workflow
jobs:
  build:
    name: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Dependencies
        run: yarn

      - name: build
        run: |
          yarn c
          yarn b
          cp ./CNAME ./dist/CNAME
          cd ./dist
          sed -i "/<meta charset=\"UTF-8\">/a\    <meta name=\"google-site-verification\" content=\"${GOOGLE_VERIFICATION}\"/>" index.html

      - name: deploy
        run: yarn d
