name: github-pages

# Triggers
on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:

# workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Dependencies
        run: yarn

      - name: Generate
        run: |
          yarn c
          yarn b
          cp ./CNAME ./dist/CNAME
          sed -i "/<meta charset=\"UTF-8\">/a\    <meta name=\"google-site-verification\" content=\"${GOOGLE_VERIFICATION}\"/>" ./dist/index.html

      - name: Deploy
        run: |
          cd ./dist
          git init
          git config user.name "Elvis"
          git config user.email "levgcsc@gmail.com"
          git add .
          git commit -m "Feat/deploy Jasmine"
          git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/lev-gc/lev-gc.github.io.git" master:master
